site_name: ENGINEER1
copyright: hub-ology 2020-2021

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/engineer1org
      name: engineer1 on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/hub-ology
      name: hub-ology on github

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
      separator: "-"
      toc_depth: 3

nav:
  - Home: 'index.md'
  - Contact: 'contact.md'
  - Donate: 'donate.md'
  - 'Hardware Kits': 'hardware-kits.md'
  - 'Labs': 'labs.md'
  - 'Sessions': 'sessions.md'  
  - 'Topics':
      - 'Allyship': 'allyship.md'
      - 'Architecture': 'architecture.md'
      - 'Communication': 'communication.md'
      - 'Finance': 'finance.md'
      - 'Infrastructure': 'infrastructure.md'
      - 'Intellectual Property': 'intellectual-property.md'      
      - 'Renewable Energy': 'renewable-energy.md'  
  - 'License': 'license.md'
  

theme:
  logo: images/engineer1-symbol.svg
  name: material
  palette:
      accent: deep purple
      primary: white

      