# This workflow will install Python dependencies and generate the static site using poetry and mkdocs

name: Engineer1 build and package 

on:
  workflow_dispatch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Staging
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install

    - name: Generate site
      run: |
        poetry run mkdocs build

    - name: Deploy
      uses: reggionick/s3-deploy@v3
      with:
        folder: site
        bucket: ${{ secrets.S3_BUCKET }}
        bucket-region: ${{ secrets.S3_BUCKET_REGION }}
        delete-removed: true
        no-cache: true
        private: true
